{% set name = "darkgraylib" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/darkgraylib-{{ version }}.tar.gz
  sha256: 71dda4af47cecc3d690b38db4acae0908db51cc34c97185e5ee737bad800b306

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - toml >=0.10.0

test:
  imports:
    - darkgraylib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/akaihola/darkgraylib
  summary: Common supporting code for Darker and Graylint
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akaihola
