{% set name = "darkgraylib" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/darkgraylib-{{ version }}.tar.gz
  sha256: 240b993a5492b3f6f68f305a409e87d146fc55768368dd783483bda0ae38ea5d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - black >=21.5b1
    - toml >=0.10.0

test:
  imports:
    - darkgraylib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/akaihola/darkgraylib
  summary: Common supporting code for Darker and Graylint
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akaihola
