{% set name = "darkgraylib" %}
{% set version = "2.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/darkgraylib-{{ version }}.tar.gz
  sha256: 032df9cf2a545573f4492a9c03cd70ea6264ebddaabf973ea02a02fdb6aed6f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=67.8.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - toml >=0.10.0

test:
  imports:
    - darkgraylib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/akaihola/darkgraylib
  summary: Common supporting code for Darker and Graylint
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akaihola
